# Idee der Householdertransformation

In [47]:
import numpy as np

In [48]:
np.set_printoptions(precision=2,suppress=True)

In [49]:
A = np.array([[3, 9, 12, 12], [-2, -5, 7, 2], [6, 12, 18, 6],  [3, 7, 38, 14]])
print('A=\n', A)

A=
 [[ 3  9 12 12]
 [-2 -5  7  2]
 [ 6 12 18  6]
 [ 3  7 38 14]]


In [50]:
R = np.array([[6, 12, 18, 6], [0, 3, 3, 9], [0, 0, 28, 8],  [0, 0, 0, 3]])
L = np.array([[1, 0, 0, 0], [1./2, 1, 0, 0], [1/2, 1/3, 1, 0],  [-1/3, -1/3, 1/2, 1]])
P = np.array([[0, 0, 1, 0], [1, 0, 0, 0], [0, 0, 0, 1],  [0, 1, 0, 0]])
print('R=\n', R, '\nL=\n', L, '\nP=\n', P)

R=
 [[ 6 12 18  6]
 [ 0  3  3  9]
 [ 0  0 28  8]
 [ 0  0  0  3]] 
L=
 [[ 1.    0.    0.    0.  ]
 [ 0.5   1.    0.    0.  ]
 [ 0.5   0.33  1.    0.  ]
 [-0.33 -0.33  0.5   1.  ]] 
P=
 [[0 0 1 0]
 [1 0 0 0]
 [0 0 0 1]
 [0 1 0 0]]


In [51]:
print('L@R=\n', L@R)
print('P@A=\n', P@A)
print('L@R - P@A=\n', L@R-P@A)

L@R=
 [[ 6. 12. 18.  6.]
 [ 3.  9. 12. 12.]
 [ 3.  7. 38. 14.]
 [-2. -5.  7.  2.]]
P@A=
 [[ 6 12 18  6]
 [ 3  9 12 12]
 [ 3  7 38 14]
 [-2 -5  7  2]]
L@R - P@A=
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [52]:
import scipy.linalg as sc

P_scipy, L, R = sc.lu(A)


In [54]:
print('P_scipy=\n', P_scipy)
print('\nP_scipy@L@R=\n', P_scipy@L@R)
print('\nA=\n', A)
print('\nA - P_scipy@L@R=\n', A-P_scipy@L@R)
print('\nP - P_scipy.T=\n', P-P_scipy.T)


P_scipy=
 [[0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]]

P_scipy@L@R=
 [[ 3.  9. 12. 12.]
 [-2. -5.  7.  2.]
 [ 6. 12. 18.  6.]
 [ 3.  7. 38. 14.]]

A=
 [[ 3  9 12 12]
 [-2 -5  7  2]
 [ 6 12 18  6]
 [ 3  7 38 14]]

A - P_scipy@L@R=
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

P - P_scipy.T=
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
