# QR mit Gram-Schmitt

In [1]:
import matplotlib.pyplot as plt
import numpy as np
from ipywidgets import interactive
from numpy.linalg import norm

In [50]:
np.set_printoptions(precision=2,suppress=True)

In [3]:
A = np.array([[1,  -2,  3],
       [-5, 1,  1],
       [2, -1,  3]
       ],dtype=float)
print(A)

[[ 1. -2.  3.]
 [-5.  1.  1.]
 [ 2. -1.  3.]]


In [5]:
u0 = A[:, 0]/np.linalg.norm(A[:, 0])
u1 = A[:, 1]-np.dot(A[:, 1], u0)*u0
u1 = u1/np.linalg.norm(u1)
u2 = A[:, 2]-np.dot(A[:, 2], u0)*u0-np.dot(A[:, 2], u1)*u1
u2 = u2/np.linalg.norm(u2)

Q = np.array([u0, u1, u2]).T
print(Q)

R = np.array([[np.dot(A[:, 0], u0), np.dot(A[:, 1], u0), np.dot(A[:, 2], u0)],
              [0, np.dot(A[:, 1], u1), np.dot(A[:, 2], u1)],
              [0, 0, np.dot(A[:, 2], u2)]])
print(R)

print(Q@R-A)

[[ 0.18257419 -0.9358192  -0.30151134]
 [-0.91287093 -0.27524094  0.30151134]
 [ 0.36514837 -0.22019275  0.90453403]]
[[ 5.47722558 -1.64316767  0.73029674]
 [ 0.          1.81659021 -3.7432768 ]
 [ 0.          0.          2.11057941]]
[[-1.11022302e-16  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-2.22044605e-16  0.00000000e+00  0.00000000e+00]]
